name: clean_slate
description: A app to be tested on medical for the primary classification of pneumonia and some other diseases. The user can select a picture from their gallery or camera and select which disease they want to check on. After a while he will be promted positive or negative depending on the case.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # tflite loading package
  tflite: ^1.0.4

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1+8
  dots_indicator: ^1.0.0
  dotted_border: ^1.0.3
  flutter_launcher_icons: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#FAB72B"

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png

  fonts:
    - family: MontserratAlternates-Bold
      fonts:
        - asset: assets/fonts/MontserratAlternates-Bold.ttf
    - family: MontserratAlternates-Regular
      fonts:
        - asset: assets/fonts/MontserratAlternates-Regular.ttf
